[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
topic = "customers/data_request"
uri = "https://parcelpilot.ca/webhooks/customers_data_request"

[[webhooks.subscriptions]]
topic = "customers/redact"
uri = "https://parcelpilot.ca/webhooks/customers_redact"

[[webhooks.subscriptions]]
topic = "shop/redact"
uri = "https://parcelpilot.ca/webhooks/shop_redact"
