name = "ParcelPilot"
client_id = "3213dab65821e57efe779dbf6da6e612"
application_url = "https://parcelpilot.ca"
embedded = true
webhooks_path = "/webhooks"
api_version = "2024-07"

[auth]
redirect_urls = ["https://parcelpilot.ca/auth/callback"]
logout_redirect_url = "https://parcelpilot.ca"

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "https://parcelpilot.ca/webhooks/customers_data_request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "https://parcelpilot.ca/webhooks/customers_redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "https://parcelpilot.ca/webhooks/shop_redact"

